name: Step 2, Data Privacy

on:
  workflow_dispatch:
  push:
    paths:
      - "PRIVACY.md"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_add_privacy:
    name: On Add Privacy Policy
    needs: get_current_step
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 2 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check PRIVACY.md
        uses: skills/action-check-file@v1
        with:
          file: "PRIVACY.md"
          search: "Data Isolation"
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
