name: Step 3, Enterprise Governance

on:
  workflow_dispatch:
  push:
    paths:
      - "enterprise-governance.yml"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_add_governance:
    name: On Add Enterprise Governance
    needs: get_current_step
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check enterprise-governance.yml
        uses: skills/action-check-file@v1
        with:
          file: "enterprise-governance.yml"
          search: "public_code_filter: blocked"
      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
